endpoints:
  metrics:
    sensitive: false

hystrix:
  command:
    default:
      execution:
        timeout: enabled
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  security:
    enabled: false




